name: Check action secrets

on:
  push:
    paths:
    - '.github/workflows/*.yml'
    branches:
    - 'main'
    - 'master'
  schedule:
  - cron: '23 1 * * *' # sync-with-template: adjust
  workflow_dispatch: { }

permissions:
  id-token: write

concurrency:
  group: check-action-secrets-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-action-secrets:
    name: Check action secrets
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Get GitHub Token
      id: get-token
      uses: remal/github-repository-token-issuer@v1
      with:
        scopes: |
          secrets: read
          members: read

    - name: Check action secrets
      uses: remal-github-actions/check-action-secrets@v1
      with:
        githubToken: ${{steps.get-token.outputs.token}}
